sudo: required
language: generic
before_install:
- sudo add-apt-repository -y ppa:avsm/ppa
- sudo apt-get update -y
- sudo apt-get install -y ocaml opam llvm-3.8
- opam init --auto-setup
- opam install -y ocamlfind llvm.3.8
- PATH=~/.opam/system/bin/:$PATH
- cd gantry && make
- ./test_all.sh
notifications:
  slack: pltworkspace:lcBQ7i4QQKLgftBnCPu1HHRL
